name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: npm install
      - name: buld storybook
        run: npm run build:storybook
      - name: run e2e tests
        run: npm run test:e2e
      - name: run lint checks
        run: npm run lint
      - name: run i18n translations check
        run: npm run i18n:check
      - name: install PW browsers
        run: npx playwright install --with-deps chromium
      - name: run basic tests
        run: playwright test --config=playwright.config.ts --project=chrome --reporter=list
      - name: run automated e2e tests
        run: playwright test --config=e2e.config.ts --project=chrome --reporter=list
